Various block placement fixes and fix calling BlockPlaceEvent
oraxen/oraxen pull request #1343
Opened 2024-04-15 01:08 UTC by minustenchan

title

2024-04-15 09:03 UTC, Boy0000 requested changes

2024-04-15 09:03 UTC, Boy0000 commented on core/src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/custom_block/CustomBlockHelpers.java
> +        if (newData != null) newMechanic = OraxenBlocks.getCustomBlockMechanic(newData);
Believe i changed this method to take a nullable mechanic as an argument
to avoid needing to refetch the same mechanic

2024-04-15 09:03 UTC, Boy0000 commented on v1_19_R1/src/main/java/io/th0rgal/oraxen/nms/v1_19_R1/NMSHandler.java
> +            return result;
inline this to
```java
return player.isSneaking() ? result : serverPlayer.gameMode.useItem(...)
```

2024-04-16 06:36 UTC, minustenchan commented
Trying to place a door against a custom block places a half door on top with a different direction for some reason lmk if u know why
https://github.com/oraxen/oraxen/assets/134551265/40330251-8878-49de-a7d8-77178f2d2a20

2024-04-16 12:36 UTC, minustenchan commented
@Boy0000 review again please, should be good to merge now

2024-04-16 15:21 UTC, Boy0000 commented
> Fix calling BlockPlaceEvent when placing regular block against custom block if target block is the same as the new block data

seems to not place it but still triggers BlockPlaceEvent

https://github.com/oraxen/oraxen/assets/62521371/93ec621e-c5a5-4c44-9d05-ec8e4cb87cc8

@minustenchan also u should be able to "Re-request review" for future 👍 
![image](https://github.com/oraxen/oraxen/assets/62521371/3b174d93-969a-4769-837d-cad229a6181e)

2024-04-16 15:30 UTC, Boy0000 approved these changes

2024-04-17 14:52 UTC, merged