Smelt Mechanic
oraxen/oraxen pull request #502
Opened 2022-09-30 11:16 UTC by ClickNinYT

Read commit description for more information.

2022-09-30 17:55 UTC, Boy0000 requested changes

2022-09-30 17:55 UTC, Boy0000 commented on src/main/java/io/th0rgal/oraxen/mechanics/provided/misc/smelt/SmeltMechanicListener.java
> +                    return;
make this a switch statement instead

2022-09-30 17:55 UTC, Boy0000 commented on src/main/java/io/th0rgal/oraxen/mechanics/provided/misc/smelt/SmeltMechanicListener.java
> +            if (furnace.getState() instanceof Furnace) {
personally prefer ! checks here leading to return instead of looping it in like this

`if (!mechanic.isHasReplacement()) return`

2022-09-30 17:55 UTC, Boy0000 commented on src/main/java/io/th0rgal/oraxen/mechanics/provided/misc/smelt/SmeltMechanic.java
> +    }
this should be hasReplacement

2022-09-30 17:55 UTC, Boy0000 commented on src/main/java/io/th0rgal/oraxen/mechanics/MechanicsManager.java
> +        registerMechanicFactory("smelt", SmeltMechanicFactory::new);
also need to add an entry under` mechanics.yml`

2022-10-01 03:57 UTC, ClickNinYT commented
Implemented requested changes.

2022-10-01 07:55 UTC, Boy0000 requested changes
last few changes and its good

2022-10-01 07:55 UTC, Boy0000 commented on src/main/java/io/th0rgal/oraxen/mechanics/provided/misc/smelt/SmeltMechanicListener.java
> +                case "minecraft_item": furnaceInventory.setFuel(new ItemStack(Objects.requireNonNull(Material.getMaterial(mechanic.getReplacementItem()))));
this might be better as `minecraft_type` as i believe thats what we use elsewhere for material

2022-10-01 07:55 UTC, Boy0000 commented on src/main/java/io/th0rgal/oraxen/mechanics/provided/misc/smelt/SmeltMechanicListener.java
> +                case "curcible_item": furnaceInventory.setFuel(MythicCrucible.core().getItemManager().getItemStack(mechanic.getReplacementItem()));
`crucible_item` not `curcible`

2022-10-01 07:55 UTC, Boy0000 commented on src/main/java/io/th0rgal/oraxen/mechanics/provided/misc/smelt/SmeltMechanicListener.java
> +            switch(mechanic.getReplacementItemType().toLowerCase()) {
you could make this entire switch statement inside `furnaceInventory.setFuel` aswell as u wanna do that in all cases

2022-10-01 09:39 UTC, ClickNinYT commented
Done.

2022-10-01 15:40 UTC, Boy0000 commented
Got a config example for this? @ClickNinYT

2022-10-01 15:48 UTC, Boy0000 commented
There is also already a "smelting mechanic" so the naming is probably confusing
If this is purely for making an item work as fuel in a furnace this should probably be renamed to something more fitting

Also not sure if this interacts nicely with furnace recipes in terms of burntime
Like the item thats being cooked has a basetime but how does this interact with that time etc

2022-10-01 15:49 UTC, Boy0000 requested changes
There is also already a "smelting mechanic" so the naming is probably confusing
If this is purely for making an item work as fuel in a furnace this should probably be renamed to something more fitting

Also not sure if this interacts nicely with furnace recipes in terms of burntime
Like the item thats being cooked has a basetime but how does this interact with that time etc

2022-10-01 22:49 UTC, ClickNinYT commented
AFAIK the item being cooked doesnt affect the burn time, as the burn time is from the fuel item. You could also create a unlimited coal by just setting the burn time to max integer.

The smelting mechanic iirc is for pickaxe where it will drop the ingot of the iron/gold ore instead of raw.

2022-10-02 07:01 UTC, Boy0000 commented
> AFAIK the item being cooked doesnt affect the burn time, as the burn time is from the fuel item. You could also create a unlimited coal by just setting the burn time to max integer.
ok makes sense

> The smelting mechanic iirc is for pickaxe where it will drop the ingot of the iron/gold ore instead of raw.
yteah still the name is confusing imo and should be renamed here

2022-11-26 10:35 UTC, Boy0000 commented
Closing due to inactivity, just recommit if u wanna pick this up again

2022-11-26 10:35 UTC, closed without merging